title: Python Fluency Workbooks
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  nancynobody

# Site Collections (like posts but without pesky date/time requirements)
collections:
  notebooks:
    output: true
    # order:
    #   - hello-world.md
    #   - introduction.md
    #   - concepts/basics.md
    #   - concepts/advanced.md

# Customize navigation links
# Set which pages you want to appear in the navigation area and configure order of the links.
header_pages:
  - pages/about.md
  # - about.markdown
# Build settings
theme: minima
# minima:
#   skin: sunrise
# remote_theme: THEME-NAME
plugins:
  - jekyll-feed

# EXCLUDE from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - tools

# Google Analytics (will only appear in production, i.e., JEKYLL_ENV=production)
# To enable, add the following lines to your Jekyll site
#   google_analytics: UA-NNNNNNNN-N

# Social Networks
# To add links to your SM accounts with icon, add the appropriate lines below
minima:
  social_links:
#     twitter: jekyllrb
    github: nancynobody
#     dribbble: jekyll
#     linkedin: jekyll