# https://github.com/mmistakes/minimal-mistakes
# remote_theme: mmistakes/minimal-mistakes
# remote_theme: "mmistakes/minimal-mistakes@4.17.2"
# remote_theme: mmistakes/minimal-mistakes@4.17.2
# remote_theme: "mmistakes/minimal-mistakes"
# remote_theme: mmistakes/minimal-mistakes --> works

# https://github.com/mmistakes/mm-github-pages-starter/blob/master/_config.yml
# remote_theme: mmistakes/minimal-mistakes --> works

remote_theme: mmistakes/mm-github-pages-starter

# remote_theme: jekyll/minima --> works

# remote_theme: nancynobody/ipynb_template_site